name: DemonMarket
main: com.tining.demonmarket.Main
version: 1.6.2
api-version: 1.13
# YAML 中的注释，一行有效
# 以上是插件基本信息，以下是命令注册
depend:
  - Vault
commands:
  demonmarket: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - dmt
    usage: |
      /mt help
      /mtadmin help
    description: Buy or sell some item in player's inventory # 描述
    permission: demonmarket.use
    permission-message: You need to have the permission to use this command. Please contact your server OP. # 无权限返回的消息，通常不用
  demonmarketadmin: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - mtadmin
      - dmtadmin
    usage: |
      /mtadmin help
    description: Buy or sell some item in player's inventory # 描述
    permission: demonmarket.admin
    permission-message: You need to have the permission to use this command. Please contact your server OP. # 无权限返回的消息，通常不用

permissions:
  demonmarket.admin:
    description: Admin
    default: op
  demonmarket.use:
    description: market use permission
    default: true
